import assert from 'node:assert/strict';
import test from 'node:test';
import { readFileSync } from 'node:fs';
import { resolve } from 'node:path';
import {
  parseAdmissionPrice, resolveAdmissionSemantic, resolveEventCardSemantics, resolveEventTypeSemantic,
} from '../scripts/ui_conformance/event-card-semantics.mjs';

const root = resolve(import.meta.dirname, '..');
const census = JSON.parse(readFileSync(resolve(root, 'tests/fixtures/ui-conformance/event-card-large-production-semantic-census.v1.json'), 'utf8'));

function event(overrides = {}) {
  return {
    event_type:'концерт', status_label:'Билеты', likes_count:0, shares_count:0,
    ticket:{kind:'ticket',label:'Купить билет',href:'https://example.invalid/ticket',status:'available',is_free:false,price_label:null,note:null},
    ...overrides,
  };
}

test('exact resolver census contains 31 labels summing to 703 and keeps broad DB evidence supporting-only', () => {
  assert.equal(census.public_projection.event_count, 703);
  assert.equal(Object.keys(census.event_type.rendered_label_counts).length, 31);
  assert.equal(Object.values(census.event_type.rendered_label_counts).reduce((total, count) => total + count, 0), 703);
  assert.deepEqual(census.event_type.observed_raw_language_leaks, ['movie', 'therapy']);
  assert.equal(census.event_type.rendered_label_counts['театр'], 1);
  assert.equal(census.event_type.rendered_label_counts.opera, undefined);
  assert.equal(census.authoritative_exact_census.sha256, '30c8ac5adfaeff17c463191714f660b3ed5d0a00aa8799e90f2be70cb1ca9993');
  assert.equal(census.authoritative_exact_census.byte_length, 11713);
  assert.match(census.authoritative_exact_census.role, /authoritative exact public-projection/u);
  assert.equal(census.supporting_raw_db_census.sha256, '3578bee41bda0b5e32e950fd1f27a2561b1ca3714ce7ac9bdd8cc4068e36ff08');
  assert.match(census.supporting_raw_db_census.role, /supporting broad raw-DB aggregate only/u);
});

test('all 31 observed labels use one component variant with semantic value plus variable label', () => {
  const rows = Object.keys(census.event_type.rendered_label_counts).map((label) => resolveEventTypeSemantic(label));
  assert.deepEqual(new Set(rows.map((row) => row.component_variant)), new Set(['default']));
  assert.equal(new Set(rows.map((row) => row.raw_value)).size, 31);
  assert.equal(new Set(rows.map((row) => row.semantic_value)).size, 31);
  assert.equal(resolveEventTypeSemantic('movie').semantic_value, 'movie');
  assert.equal(resolveEventTypeSemantic('movie').label, 'movie');
  assert.equal(resolveEventTypeSemantic('therapy').label, 'therapy');
  assert.equal(resolveEventTypeSemantic('день открытых дверей').semantic_value, 'день-открытых-дверей');
  const override = resolveEventTypeSemantic('концерт', { labelOverride:'Музыка сегодня' });
  assert.equal(override.semantic_value, 'концерт');
  assert.equal(override.label, 'Музыка сегодня');
  assert.equal(override.component_variant, 'default');
});

test('price is content, not a component variant, and supports single/range plus explicit/default currency', () => {
  assert.deepEqual(parseAdmissionPrice('1500–2000 ₽'), {
    valid:true, reason:null, label:'1500–2000 ₽', amount_min:1500, amount_max:2000,
    currency:'RUB', currency_source:'label', amount_kind:'range',
  });
  assert.deepEqual(parseAdmissionPrice('25 EUR'), {
    valid:true, reason:null, label:'25 EUR', amount_min:25, amount_max:25,
    currency:'EUR', currency_source:'label', amount_kind:'single',
  });
  const defaultCurrency = parseAdmissionPrice('900', { defaultCurrency:'KZT' });
  assert.equal(defaultCurrency.currency, 'KZT');
  assert.equal(defaultCurrency.currency_source, 'default');
  assert.equal(resolveAdmissionSemantic(event({ticket:{...event().ticket,price_label:'1500–2000 ₽'}})).component_variant, 'default');
  const structured = resolveAdmissionSemantic(event({ticket:{...event().ticket,price_label:null,amount_min:15,amount_max:25,currency:'EUR'}}));
  assert.equal(structured.state, 'priced');
  assert.deepEqual(structured.price, {valid:true,reason:null,label:'15–25 EUR',amount_min:15,amount_max:25,currency:'EUR',currency_source:'field',amount_kind:'range'});
});

test('all 61 prices generated by the exact Astro resolver are modeled and both 0-ruble anomalies fail closed', () => {
  const labels = census.admission.rendered_price_label_counts;
  assert.equal(Object.keys(labels).length, 61);
  assert.equal(Object.values(labels).reduce((sum, count) => sum + count, 0), census.admission.rendered_price_event_count);
  for (const [label, count] of Object.entries(labels)) {
    const price = parseAdmissionPrice(label);
    if (label === '0 ₽') {
      assert.equal(price.valid, false);
      assert.equal(price.reason, 'non-positive-price');
      assert.equal(count, 2);
    } else {
      assert.equal(price.valid, true, label);
      assert.equal(price.currency, 'RUB', label);
    }
  }
});

test('zero price and unspecified legacy copy fail closed instead of becoming valid rendered specimens', () => {
  const zero = resolveAdmissionSemantic(event({status_label:'0 ₽',ticket:{...event().ticket,price_label:'0 ₽'}}));
  assert.equal(zero.state, 'invalid_price');
  assert.equal(zero.visible, false);
  assert.equal(zero.label, null);
  assert.equal(zero.anomaly, 'non-positive-price');
  const unspecified = resolveAdmissionSemantic(event({status_label:'Условия уточняются',ticket:{kind:'status',label:'Условия уточняются',href:null,status:null,is_free:false,price_label:null,note:null}}));
  assert.equal(unspecified.state, 'unspecified');
  assert.equal(unspecified.visible, false);
  assert.equal(unspecified.label, null);
  assert.equal(unspecified.anomaly, 'obsolete-unspecified-label-hidden');
});

test('admission state, CTA actions and social-proof content remain separate semantic axes', () => {
  const semantics = resolveEventCardSemantics(event({likes_count:381,shares_count:116}), {calendarEligible:true});
  assert.equal(semantics.admission.state, 'ticketed');
  assert.equal(semantics.admission_cta.semantic_action, 'purchase');
  assert.equal(semantics.admission_cta.enabled, true);
  assert.equal(semantics.actions.calendar.semantic_action, 'calendar_add');
  assert.equal(semantics.actions.like.semantic_action, 'like');
  assert.deepEqual(semantics.social_proof.like, {component_id:'event.social-proof.like',metric:'like',count:381,visible:true,count_label:'381',component_variant:'default'});
  assert.deepEqual(semantics.social_proof.share, {component_id:'event.social-proof.share',metric:'share',count:116,visible:true,count_label:'116',component_variant:'default'});
  const absentProof = resolveEventCardSemantics(event(), {calendarEligible:false});
  assert.equal(absentProof.actions.like.present, true);
  assert.equal(absentProof.social_proof.like.visible, false);
  assert.equal(absentProof.social_proof.like.count_label, '');
  assert.equal(absentProof.actions.calendar.present, false);
});

test('authoritative census state totals and visibility decisions remain exact', () => {
  assert.equal(Object.values(census.admission.source_state_counts).reduce((sum, count) => sum + count, 0), 703);
  assert.equal(census.admission.invalid_zero_price_count, 2);
  assert.equal(census.actions_and_social.social_proof.like.positive + census.actions_and_social.social_proof.like.absent, 703);
  assert.equal(census.actions_and_social.social_proof.share.positive + census.actions_and_social.social_proof.share.absent, 703);
  assert.equal(census.actions_and_social.calendar.eligible + census.actions_and_social.calendar.absent, 703);
  assert.equal(census.event_type.component_variant_count, 1);
});
