#!/usr/bin/env node
import { createHash } from 'node:crypto';
import { cpSync, existsSync, mkdirSync, readFileSync, readdirSync, statSync, writeFileSync } from 'node:fs';
import { basename, dirname, join, relative, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import { BEHAVIOR_SCHEMA, BEHAVIOR_STATUS, assertBehavioralSupplement } from '../behavioral.mjs';
import { buildBehaviorPacketRegistry } from './registry.mjs';
import { assertBehaviorCaptureComplete, assertBehaviorObservation, assertBehaviorPacketRegistry } from './validate.mjs';

export const BEHAVIOR_SUPPLEMENT_ID='behavioral-supplement-v1.1-snapshot-20260808T124842-4786ac53bc';
export const REVIEW_SCHEMA='current_ui_behavioral_visual_review_v1_1';
export const ARTIFACT_METADATA_SCHEMA='current_ui_behavioral_artifact_provenance_v1_1';
const sha=(value)=>createHash('sha256').update(value).digest('hex');
const stable=(value)=>Array.isArray(value)?value.map(stable):value&&typeof value==='object'?Object.fromEntries(Object.keys(value).sort().map((key)=>[key,stable(value[key])])):value;
const json=(value,pretty=false)=>`${JSON.stringify(stable(value),null,pretty?2:0)}\n`;
const readJson=(path)=>JSON.parse(readFileSync(path,'utf8'));
const readJsonl=(path)=>readFileSync(path,'utf8').split('\n').filter(Boolean).map(JSON.parse);
const writeJsonl=(path,rows)=>writeFileSync(path,rows.slice().sort((a,b)=>a.id.localeCompare(b.id)).map((row)=>json(row)).join(''));
function walk(root){const rows=[];for(const entry of readdirSync(root,{withFileTypes:true}).sort((a,b)=>a.name.localeCompare(b.name))){const path=join(root,entry.name);if(entry.isDirectory())rows.push(...walk(path));else if(entry.isFile())rows.push(path);}return rows;}
function mediaType(path){return path.endsWith('.jsonl')?'application/x-ndjson':path.endsWith('.json')?'application/json':path.endsWith('.md')?'text/markdown':path.endsWith('.png')?'image/png':'application/octet-stream';}
function safeRelative(path,label){if(!/^[a-z0-9._/-]+$/iu.test(path)||path.includes('..')||path.startsWith('/'))throw new Error(`Unsafe ${label} path: ${path}`);return path;}
function outputEntry(path){const bytes=readFileSync(path);return {bytes:bytes.length,sha256:sha(bytes),media_type:mediaType(path),records:path.endsWith('.jsonl')?bytes.toString('utf8').split('\n').filter(Boolean).length:null};}
function requiredReviewMap(reviewLedgerPath){if(!reviewLedgerPath)return null;const rows=readJsonl(resolve(reviewLedgerPath));const map=new Map();for(const row of rows){if(row.schema_version!==REVIEW_SCHEMA||row.review_status!=='reviewed-full-resolution'||row.full_resolution_opened!==true||!row.reviewer||!row.reviewed_at||!row.path||!row.sha256)throw new Error(`Invalid full-resolution review row: ${row.id||'unknown'}`);if(map.has(row.observation_id))throw new Error(`Duplicate observation review: ${row.observation_id}`);map.set(row.observation_id,row);}return map;}
function defaultArtifactMetadata(){return {schema_version:ARTIFACT_METADATA_SCHEMA,supplement_id:BEHAVIOR_SUPPLEMENT_ID,status:'capture-generated-provenance-pending',actions:{repository:process.env.GITHUB_REPOSITORY||null,workflow:process.env.GITHUB_WORKFLOW||null,run_id:process.env.GITHUB_RUN_ID||null,run_attempt:process.env.GITHUB_RUN_ATTEMPT||null,run_url:process.env.GITHUB_SERVER_URL&&process.env.GITHUB_REPOSITORY&&process.env.GITHUB_RUN_ID?`${process.env.GITHUB_SERVER_URL}/${process.env.GITHUB_REPOSITORY}/actions/runs/${process.env.GITHUB_RUN_ID}`:null,artifact_id:null,artifact_name:'current-ui-behavioral-decoder-v1-1-capture',artifact_url:null,digest:null,bytes:null,created_at:null,expires_at:null},permanent_storage:{status:'pending',release_tag:null,asset_id:null,asset_name:null,url:null,sha256:null,bytes:null},independent_audit:{status:'pending',reviewer:null,commit:null,report_sha256:null},secret_scan:{status:'pending'}};}
function assertFinalMetadata(metadata){if(metadata.schema_version!==ARTIFACT_METADATA_SCHEMA||metadata.supplement_id!==BEHAVIOR_SUPPLEMENT_ID)throw new Error('Behavior artifact metadata identity mismatch');const actions=metadata.actions||{};if(!actions.repository||!actions.workflow||!actions.run_id||!actions.run_attempt||!actions.run_url||!actions.artifact_id||!actions.artifact_name||!actions.artifact_url||!/^sha256:[a-f0-9]{64}$/u.test(actions.digest||'')||!actions.bytes||!actions.created_at||!actions.expires_at)throw new Error('Actions artifact metadata incomplete');const permanent=metadata.permanent_storage||{};if(permanent.status!=='durable'||!permanent.release_tag||!permanent.asset_id||!permanent.asset_name||!permanent.url||!/^[a-f0-9]{64}$/u.test(permanent.sha256||'')||!permanent.bytes)throw new Error('Permanent evidence metadata incomplete');const audit=metadata.independent_audit||{};if(audit.status!=='PASS'||!audit.reviewer||!audit.commit||!/^[a-f0-9]{64}$/u.test(audit.report_sha256||''))throw new Error('Independent audit metadata incomplete');if(metadata.secret_scan?.status!=='PASS')throw new Error('Secret scan is not PASS');}
function validateRaster(captureRoot,observation){assertBehaviorObservation(observation);const rel=safeRelative(observation.screenshot.path,'raster');const path=resolve(captureRoot,rel);if(!path.startsWith(`${resolve(captureRoot)}/`)||!existsSync(path)||!statSync(path).isFile())throw new Error(`Behavior raster missing: ${rel}`);const bytes=readFileSync(path);if(bytes.length!==observation.screenshot.bytes||sha(bytes)!==observation.screenshot.sha256)throw new Error(`Behavior raster identity mismatch: ${rel}`);return {rel,path,bytes};}
function report({sourceManifest,status,plans,observations,blockers,reviews,metadata}){const counts=Object.fromEntries(['mobile-menu','disclosure','overlay','selection','rail','sticky','cta','transport','media','loading'].map((family)=>[family,plans.filter((row)=>row.family===family).length]));return `# Current UI Behavioral Decoder & Experiment Archaeology v1.1\n\n- Supplement: \`${BEHAVIOR_SUPPLEMENT_ID}\`\n- Immutable Decoder v1 manifest SHA-256: \`${sourceManifest.base_snapshot.manifest_sha256}\`\n- Exact source SHA: \`${sourceManifest.source_sha}\`\n- Status: **${status}**\n- Behavioral packets: ${plans.length} (${plans.filter((row)=>row.capture_status==='explicit-blocker').length} exact blockers)\n- Captured phases / rasters: ${observations.length}\n- Full-resolution visual reviews: ${reviews.length}\n- Family counts: \`${JSON.stringify(counts)}\`\n- Actions run: ${metadata.actions?.run_url||'pending'}\n- Permanent evidence: ${metadata.permanent_storage?.url||'pending'}\n- Independent audit: ${metadata.independent_audit?.status||'pending'}\n\n## Evidence boundary\n\nThis is append-only AS-IS behavioral evidence. Controlled exact-source runtime does not become production observation. Explicit blockers remain blockers rather than synthetic captures. The supplement does not authorize merge, split, deletion, normalization, tokenization, Penpot mutation, production Astro/CSS/JS changes, or an experiment winner.\n\n## Required reconciliation retained\n\nThe 4:5 EventCard and 5:4 mobile-rail specimens remain separate consumer contracts. Editorial/landscape and split/portrait Event Detail keep different CTA anatomy. All three transport treatments remain controlled-only and NOT_MERGED; production remains forced off without a winner receipt.\n`;
}

export function materializeBehavioralEvidence({sourceSupplementRoot,captureRoot,outputRoot,reviewLedgerPath=null,artifactMetadataPath=null}){
  const source=resolve(sourceSupplementRoot);const capture=resolve(captureRoot);const root=resolve(outputRoot);assertBehavioralSupplement(source,{allowIncomplete:true});
  const registry=buildBehaviorPacketRegistry();assertBehaviorPacketRegistry(registry);const rawObservations=readJsonl(join(capture,'behavior-specimen-observations.jsonl'));const blockerRows=readJsonl(join(capture,'behavior-capture-blockers.jsonl'));assertBehaviorCaptureComplete(registry,rawObservations,blockerRows);
  const reviewMap=requiredReviewMap(reviewLedgerPath);const reviewed=Boolean(reviewMap);const metadata=artifactMetadataPath?readJson(resolve(artifactMetadataPath)):defaultArtifactMetadata();if(reviewed)assertFinalMetadata(metadata);
  mkdirSync(root,{recursive:true});for(const path of walk(source)){const rel=relative(source,path);if(['manifest.json','receipt.json','audit-report.md','artifact-receipt.json','artifact-index.json','independent-audit.json'].includes(rel))continue;mkdirSync(dirname(join(root,rel)),{recursive:true});cpSync(path,join(root,rel));}
  const rasterMap=new Map();for(const observation of rawObservations){const raster=validateRaster(capture,observation);rasterMap.set(observation.id,raster);}
  if(reviewed){if(reviewMap.size!==rawObservations.length)throw new Error(`Review ledger coverage mismatch: ${reviewMap.size}/${rawObservations.length}`);for(const observation of rawObservations){const review=reviewMap.get(observation.id);const raster=rasterMap.get(observation.id);if(!review||review.path!==raster.rel||review.sha256!==observation.screenshot.sha256)throw new Error(`Review/raster mismatch: ${observation.id}`);}}
  const blockersByPlan=new Map(blockerRows.map((row)=>[row.plan_id,row]));const observationsByPlan=new Map();for(const row of rawObservations){if(!observationsByPlan.has(row.plan_id))observationsByPlan.set(row.plan_id,[]);observationsByPlan.get(row.plan_id).push(row);}
  const plans=registry.plans.map((plan)=>{const observations=(observationsByPlan.get(plan.id)||[]).sort((a,b)=>a.sequence_index-b.sequence_index);const blocker=blockersByPlan.get(plan.id)||null;return {...plan,capture_status:blocker?'explicit-blocker':reviewed?'captured-and-reviewed':'captured-not-reviewed',review_status:blocker?'not-applicable-no-raster':reviewed?'reviewed-full-resolution':'pending-human-full-resolution-review',observation_ids:observations.map((row)=>row.id),blocker_id:blocker?.id||null,expected_capture_phases:plan.steps.filter((row)=>row.capture).map((row)=>row.phase),evidence_status:blocker?'exact-blocker-recorded':reviewed?'captured-and-reviewed':'captured-not-reviewed'};});
  const observations=rawObservations.map((row)=>{const review=reviewMap?.get(row.id);return {...row,capture_status:'captured',review_status:reviewed?'reviewed-full-resolution':'pending-human-full-resolution-review',human_review:review||null,evidence_status:reviewed?'captured-and-reviewed':'captured-not-reviewed'};});
  const registryPlans=new Map(registry.plans.map((row)=>[row.id,row]));const pageVerification=observations.map((row)=>{const route=registryPlans.get(row.plan_id)?.route||'';return {schema_version:row.schema_version,id:`behavior-page-verification.${sha(row.id).slice(0,18)}`,observation_id:row.id,plan_id:row.plan_id,family:row.family,phase:row.phase,route_hash:row.route_hash,viewport:row.viewport,evidence_plane:row.evidence_plane,route_kind:route.startsWith('/behavior-specimens/')?'controlled-wrapper':route.startsWith('/lab/')?'lab-route':'exact-source-built-route-under-controlled-clock',screenshot:row.screenshot,review_status:row.review_status,production_observed:false,production_equivalence:false,decision:'NOT_MERGED'};});
  const actionPacketIndex=plans.map((plan)=>({schema_version:plan.schema_version,id:`behavior-action-index.${sha(plan.id).slice(0,18)}`,plan_id:plan.id,family:plan.family,initial_state:plan.steps[0]?.phase||null,action_sequence:plan.steps.flatMap((step)=>step.actions.map((action)=>({before_phase:step.phase,...action}))),final_state:plan.steps.at(-1)?.phase||null,observation_ids:plan.observation_ids,blocker_id:plan.blocker_id,coverage_status:plan.capture_status,review_status:plan.review_status,focus_and_scroll_in_observations:plan.observation_ids.length>0,decision:'NOT_MERGED'}));
  const visualReviews=observations.map((row)=>reviewMap?.get(row.id)||{schema_version:REVIEW_SCHEMA,id:`behavior-review.${sha(row.id).slice(0,18)}`,observation_id:row.id,plan_id:row.plan_id,path:row.screenshot.path,sha256:row.screenshot.sha256,media_type:'image/png',review_status:'pending-human-full-resolution-review',full_resolution_opened:false,visual_result:null,reviewer:null,reviewed_at:null,decision:'NOT_MERGED'});
  const unresolved=readJsonl(join(source,'unresolved.jsonl')).filter((row)=>!(reviewed&&row.id==='unresolved.behavioral-packets-pending'));
  for(const blocker of blockerRows)unresolved.push({id:`unresolved.${blocker.id}`,kind:'exact-behavioral-capture-blocker',plan_id:blocker.plan_id,family:blocker.family,observed_fact:blocker.reason,source_path:blocker.source_path,status:'exact-blocker-recorded',blocks_ready:false,decision:'NOT_MERGED'});
  unresolved.push({id:'unresolved.listing-filter-mobile-bottom-nav-collision',kind:'controlled-runtime-layout-conflict',plan_id:'behavior-packet.floating-filter-footer-collision',observed_fact:'At the pinned 390px consumer the floating ListingPersonalFilter occupies the same bottom edge as MobileBottomNav; the packet records the collision without changing either implementation.',status:'conflict',blocks_ready:false,decision:'NOT_MERGED'});
  if(!reviewed&&!unresolved.some((row)=>row.id==='unresolved.behavioral-packets-pending'))unresolved.push({id:'unresolved.behavioral-packets-pending',kind:'capture-and-review-gate',observed_fact:'Behavior rasters are captured but still require file-level full-resolution human review and durable provenance.',blocks_ready:true,decision:'NOT_MERGED'});
  const replacements={'behavior-specimen-plan.jsonl':plans,'behavior-specimen-observations.jsonl':observations,'behavior-page-verification.jsonl':pageVerification,'action-packet-index.jsonl':actionPacketIndex,'visual-review-ledger.jsonl':visualReviews,'unresolved.jsonl':unresolved};for(const [name,rows] of Object.entries(replacements))writeJsonl(join(root,name),rows);
  const sourceManifest=readJson(join(source,'manifest.json'));const status=reviewed?BEHAVIOR_STATUS:'EVIDENCE_COLLECTION_INCOMPLETE';const audit=report({sourceManifest,status,plans,observations,blockers:blockerRows,reviews:reviewed?visualReviews:[],metadata});writeFileSync(join(root,'audit-report.md'),audit);
  writeFileSync(join(root,'artifact-receipt.json'),json({...metadata,status:reviewed?'complete':'capture-complete-review-pending',source_sha:sourceManifest.source_sha,base_snapshot:sourceManifest.base_snapshot,behavior_packet_count:plans.length,observation_count:observations.length,raster_count:rasterMap.size,review_count:reviewed?visualReviews.length:0},true));
  writeFileSync(join(root,'independent-audit.json'),json(metadata.independent_audit||{status:'pending'},true));
  const compactEntries=walk(root).filter((path)=>!['manifest.json','receipt.json','artifact-index.json'].includes(basename(path))).map((path)=>({path:relative(root,path),storage:'compact-supplement',...outputEntry(path)}));const heavyEntries=observations.map((row)=>{const raster=rasterMap.get(row.id);return {path:raster.rel,storage:'actions-and-permanent-heavy-artifact',bytes:raster.bytes.length,sha256:sha(raster.bytes),media_type:'image/png',observation_id:row.id,review_status:row.review_status};});const artifactIndex={schema_version:BEHAVIOR_SCHEMA,supplement_id:BEHAVIOR_SUPPLEMENT_ID,status:reviewed?'reviewed-durable':'capture-complete-review-pending',base_snapshot:sourceManifest.base_snapshot,actions:metadata.actions,permanent_storage:metadata.permanent_storage,entries:[...compactEntries,...heavyEntries].sort((a,b)=>a.path.localeCompare(b.path))};writeFileSync(join(root,'artifact-index.json'),json(artifactIndex,true));
  const outputFiles=walk(root).filter((path)=>!['manifest.json','receipt.json'].includes(basename(path)));const outputs=Object.fromEntries(outputFiles.map((path)=>[relative(root,path),outputEntry(path)]));const manifest={...sourceManifest,schema_version:BEHAVIOR_SCHEMA,supplement_id:BEHAVIOR_SUPPLEMENT_ID,supplement_version:'1.1',status,base_snapshot:{...sourceManifest.base_snapshot,path:'../decoder-v1-snapshot-20260808T124842-4786ac53bc'},immutable_v1_modified:false,constraints:{...sourceManifest.constraints,append_only:true,component_merge:false,component_split:false,component_deletion:false,normalization:false,tokens:false,production_astro_css_js:false,penpot:false,experiment_winner_decision:false},outputs,counts:{...sourceManifest.counts,behavior_packet_plans:plans.length,executable_packets:plans.filter((row)=>row.capture_status!=='explicit-blocker').length,explicit_blockers:plans.filter((row)=>row.capture_status==='explicit-blocker').length,observations:observations.length,page_verification:pageVerification.length,action_packet_index:actionPacketIndex.length,visual_reviews:reviewed?visualReviews.length:0,rasters:rasterMap.size},human_visual_review:{required:true,completed:reviewed,raster_count:rasterMap.size,reviewed_raster_count:reviewed?visualReviews.length:0,perceptual_hash_is_not_review:true,ledger_sha256:reviewed?sha(readFileSync(resolve(reviewLedgerPath))):null},provenance:{actions:metadata.actions,permanent_storage:metadata.permanent_storage,independent_audit:metadata.independent_audit},blockers:reviewed?[]:['unresolved.behavioral-packets-pending']};writeFileSync(join(root,'manifest.json'),json(manifest,true));const receipt={schema_version:BEHAVIOR_SCHEMA,supplement_id:BEHAVIOR_SUPPLEMENT_ID,status:reviewed?'complete':'partial',final_status:status,manifest_sha256:sha(readFileSync(join(root,'manifest.json'))),blockers:reviewed?[]:['unresolved.behavioral-packets-pending'],counts:{plans:plans.length,observations:observations.length,rasters:rasterMap.size,reviews:reviewed?visualReviews.length:0,explicit_blockers:blockerRows.length}};writeFileSync(join(root,'receipt.json'),json(receipt,true));assertBehavioralSupplement(root,{allowIncomplete:!reviewed});return {root,manifest,receipt,plans,observations,blockers:blockerRows,reviews:visualReviews};
}

function arg(name,fallback=null){const index=process.argv.indexOf(name);return index>=0?process.argv[index+1]??fallback:fallback;}
if(process.argv[1]===fileURLToPath(import.meta.url)){const result=materializeBehavioralEvidence({sourceSupplementRoot:arg('--source-supplement'),captureRoot:arg('--capture-root'),outputRoot:arg('--output'),reviewLedgerPath:arg('--review-ledger'),artifactMetadataPath:arg('--artifact-metadata')});process.stdout.write(json({root:result.root,status:result.receipt.final_status,plans:result.plans.length,observations:result.observations.length,blockers:result.blockers.length,reviews:result.receipt.counts.reviews},true));}
