export const BEHAVIOR_PACKET_SCHEMA='current_ui_behavior_action_packet_v1_1';
export const PINNED_SOURCE_SHA='ef7aa62e45c60f7a12da6160f490719c0721ec03';

export const ALL_BREAKPOINT_PROBE_IDS=Object.freeze([
  'breakpoint.0170569a05bc3929',
  'breakpoint.017c006b1fb4a73e',
  'breakpoint.0214ee3f2f1c58df',
  'breakpoint.0505537a7927b9e5',
  'breakpoint.056e189fa33582f4',
  'breakpoint.062bc67f6db72c09',
  'breakpoint.06ced1939a5a95ba',
  'breakpoint.082a07534e557fe1',
  'breakpoint.089f8fb223ce16a5',
  'breakpoint.092a8f35e91d132c',
  'breakpoint.0a0f3efeb08560b0',
  'breakpoint.0a49f6ee1ca21cd8',
  'breakpoint.0b762ad8402a23ab',
  'breakpoint.0d1227004996eb64',
  'breakpoint.0ed964505491feba',
  'breakpoint.104c9eb78827e8ae',
  'breakpoint.13c24df86ede9ce9',
  'breakpoint.1436c98c4e8fff69',
  'breakpoint.14b13c14df05163f',
  'breakpoint.153afa868a2150c2',
  'breakpoint.15a96375b0393749',
  'breakpoint.170772adb1fac0fd',
  'breakpoint.17cf0b9da60f5b7d',
  'breakpoint.18e09a553f004c97',
  'breakpoint.199b6778f8e95239',
  'breakpoint.1af7da8ac2444aba',
  'breakpoint.1c5991281f5bdc81',
  'breakpoint.1cc8ad8666dbfaed',
  'breakpoint.1db97eb386e678d8',
  'breakpoint.1e783fe5065ca416',
  'breakpoint.1ebd8981408e1bff',
  'breakpoint.1fe4b995561024de',
  'breakpoint.1fecfe06e9f41a09',
  'breakpoint.1ff6047bbf019dba',
  'breakpoint.201fd0278680ee46',
  'breakpoint.220e91b7c1687174',
  'breakpoint.2236ffe985f9747c',
  'breakpoint.23b491b96f811dae',
  'breakpoint.24238feb63f26805',
  'breakpoint.24b488dc7fde4885',
  'breakpoint.24e81a773f625874',
  'breakpoint.26c3e2f973d25660',
  'breakpoint.2769bf95ca191bfe',
  'breakpoint.2861e448287d8108',
  'breakpoint.294385764c3b1712',
  'breakpoint.2963ebea51928790',
  'breakpoint.29a74ab638026ed1',
  'breakpoint.2a0c93fa2d01231d',
  'breakpoint.2b71e3365f6f4029',
  'breakpoint.2b7483cd8a412386',
  'breakpoint.2bcd914b283cec91',
  'breakpoint.2cd30d1b55728af3',
  'breakpoint.2d147c16c387943a',
  'breakpoint.2e41e3e1ccd3b21e',
  'breakpoint.2e9f57a27e75afed',
  'breakpoint.2f62656743dc0793',
  'breakpoint.31c174d21ed6d7e8',
  'breakpoint.31d33f60f7ca17db',
  'breakpoint.33b7e5e77b21804c',
  'breakpoint.33fca7396863b662',
  'breakpoint.34a6a21727f8a16a',
  'breakpoint.359fd148385ad550',
  'breakpoint.371a38b9de52554b',
  'breakpoint.38404e42d7047244',
  'breakpoint.3877feea65c3dc1b',
  'breakpoint.390d21fb616032ca',
  'breakpoint.39576e5f534f2878',
  'breakpoint.3979e97ac4ac3c47',
  'breakpoint.3ac31bc17ae82f34',
  'breakpoint.3f249cc89bc6d8a0',
  'breakpoint.400843cc02155650',
  'breakpoint.4122e2de42babe09',
  'breakpoint.41336cdc16d6c91b',
  'breakpoint.41994dfa6f362d7c',
  'breakpoint.4245b5e906cbbd1f',
  'breakpoint.4385bf1991965768',
  'breakpoint.44fbef4c842d030d',
  'breakpoint.45082578917e54ab',
  'breakpoint.455146057ac1a100',
  'breakpoint.4748f35ca63b0066',
  'breakpoint.48d5fce48f5c0b5c',
  'breakpoint.4b5dc39a58ce631b',
  'breakpoint.4bdf803b6b00d6f0',
  'breakpoint.4be6cf20c68143e4',
  'breakpoint.4bf84601f6f0d7c0',
  'breakpoint.4dbadbf756abecc4',
  'breakpoint.4ded4f210c76bdbd',
  'breakpoint.4df51e317512addf',
  'breakpoint.4e09669351a6cdfb',
  'breakpoint.4e4f246495ab0829',
  'breakpoint.514400d3ea4ac33c',
  'breakpoint.515771e03e13bf5c',
  'breakpoint.54e1f363372e166f',
  'breakpoint.551909f887292efd',
  'breakpoint.55bb597691458573',
  'breakpoint.5691ff143215550b',
  'breakpoint.5696d8f1fe99dd1f',
  'breakpoint.57154df963510410',
  'breakpoint.571728f2ece2f62b',
  'breakpoint.574b40e07e855a99',
  'breakpoint.57d81be544cd5901',
  'breakpoint.595f99bfb262f7c4',
  'breakpoint.597bbd767e070254',
  'breakpoint.59de3e4fb92b6f11',
  'breakpoint.5ac135a122db8fd9',
  'breakpoint.5be6e535777ccec2',
  'breakpoint.5cbd9c5f4576418e',
  'breakpoint.5e60bfe07f87b312',
  'breakpoint.5f8e78e6fe34c449',
  'breakpoint.604c21f6ff5b1412',
  'breakpoint.611e5392a7139f5b',
  'breakpoint.61a3815f7e3e8f29',
  'breakpoint.627ab6a19c219253',
  'breakpoint.633262040f5a8fdd',
  'breakpoint.6409e64d3ede25b2',
  'breakpoint.64f8e4c8ef1c633d',
  'breakpoint.650d181f42e44269',
  'breakpoint.657255de26bb8525',
  'breakpoint.6580ba5f67bfdc8f',
  'breakpoint.65dd0dcae8b9f64a',
  'breakpoint.65e44324f178f549',
  'breakpoint.6781f2c3fc5ddc07',
  'breakpoint.68e53ae3353391c0',
  'breakpoint.6a3f29cc4a7f92db',
  'breakpoint.6a5d9fbf3efee844',
  'breakpoint.6de454426d42049c',
  'breakpoint.6e5fc6cb89f43e7a',
  'breakpoint.70b41f27fb8b7f0a',
  'breakpoint.719bd9ff598c6e05',
  'breakpoint.72545641023e2c7d',
  'breakpoint.72596c85ecc7ce14',
  'breakpoint.72deb106db9a862e',
  'breakpoint.73180bb814d5d9e2',
  'breakpoint.738e6d16498f449e',
  'breakpoint.74ff2a45a0690178',
  'breakpoint.75858e0231144158',
  'breakpoint.7587fdcf9ebf75d8',
  'breakpoint.77e39183089e1d36',
  'breakpoint.786759310c760aa0',
  'breakpoint.7d54d74c7e7c5a4c',
  'breakpoint.7d5d25e140f8045e',
  'breakpoint.7d6d6f68d5054cf9',
  'breakpoint.7da93d0f0c411d1d',
  'breakpoint.7dcef72ba1661e9b',
  'breakpoint.7e8e6a64c0bee1bb',
  'breakpoint.7eb95dfe4a10d51c',
  'breakpoint.80f9181463e915ec',
  'breakpoint.81227f2695040502',
  'breakpoint.831ca48b02b21f6a',
  'breakpoint.8458b250b193ccdc',
  'breakpoint.84e5b575c13ee50a',
  'breakpoint.858cd00b69af5be0',
  'breakpoint.86c385009693df9f',
  'breakpoint.86d75d9bd1418e1e',
  'breakpoint.87367ee0219a9acc',
  'breakpoint.8742d05d0203ff19',
  'breakpoint.87aa4f6838c918b1',
  'breakpoint.886ee5866a9599a4',
  'breakpoint.89451379486d0838',
  'breakpoint.89badc46a9a3f4ea',
  'breakpoint.8b6ce655a24f4d8f',
  'breakpoint.8c239b1c26266b81',
  'breakpoint.8c8b85a41b9dabf5',
  'breakpoint.8dd51286eadca8d6',
  'breakpoint.8df41ee0a7de7d26',
  'breakpoint.8f17ed789b443851',
  'breakpoint.9007467d208ac7bd',
  'breakpoint.9028cb65caadcea4',
  'breakpoint.920dc58423494446',
  'breakpoint.9274460842120519',
  'breakpoint.935a4e67e228b0be',
  'breakpoint.93aca2577727dc6b',
  'breakpoint.94384756c8c7c9fe',
  'breakpoint.94eaec171ed8cda0',
  'breakpoint.965adcffb2bf05cb',
  'breakpoint.9722d8751dc457a3',
  'breakpoint.9858666d0b34dad5',
  'breakpoint.987ae9721f95290a',
  'breakpoint.9a2579075d615f62',
  'breakpoint.9a400b28fde1483e',
  'breakpoint.9b30ded5288a7a33',
  'breakpoint.a006f62d5ad7e0d7',
  'breakpoint.a228a32b6f6f20bd',
  'breakpoint.a2ab8c7ff2962a9a',
  'breakpoint.a314e4ca0f923c4e',
  'breakpoint.a42d93881454fdb7',
  'breakpoint.a459d5c14b35b64c',
  'breakpoint.a59b4f32a29380d8',
  'breakpoint.a5c4ed1d2fb5595a',
  'breakpoint.a6299315b19e94fa',
  'breakpoint.a6a8e0bad0021445',
  'breakpoint.a6dd838bf45b5e86',
  'breakpoint.a7a957fa4e490e57',
  'breakpoint.a7ae3247d4e17d6d',
  'breakpoint.a894896c52e3303e',
  'breakpoint.a97d862e29e8c55f',
  'breakpoint.a9afa7637d446b77',
  'breakpoint.aacb4e635d147b7f',
  'breakpoint.ab7391eebe277fa2',
  'breakpoint.ac401f6f6a56122a',
  'breakpoint.ac44ed0d6c51d757',
  'breakpoint.ae7516ca93bce59b',
  'breakpoint.aeed0d6ea56c5c3b',
  'breakpoint.af2ae65ff20e0497',
  'breakpoint.af4e1c12a08dedce',
  'breakpoint.b0155ba76d541b3c',
  'breakpoint.b03d2b27484382aa',
  'breakpoint.b0a571dd96ff9b7a',
  'breakpoint.b0cdf9e979196697',
  'breakpoint.b2ca48a07351f5bb',
  'breakpoint.b2ed31ecff06548e',
  'breakpoint.b2f44aa14b9c66b4',
  'breakpoint.b3d774a3755e5d8e',
  'breakpoint.b5ded21567360518',
  'breakpoint.b5e3c9006345982f',
  'breakpoint.b63373b06179aa27',
  'breakpoint.b91658925c7c738b',
  'breakpoint.ba9dd7536bc768b9',
  'breakpoint.bab0717f8ac3f923',
  'breakpoint.bba5462ce00d7967',
  'breakpoint.bd0397b5b79cc6f4',
  'breakpoint.bd12c3aa25c7af0e',
  'breakpoint.bd7a5d9fe96454c8',
  'breakpoint.be06e45875265229',
  'breakpoint.be4aaad19119d6e0',
  'breakpoint.bf94cddfd75538f8',
  'breakpoint.bf9f05f8d632a7d0',
  'breakpoint.bfd91ccbe7fce6ff',
  'breakpoint.bffd5f101c73b98c',
  'breakpoint.c11beea1292f8b73',
  'breakpoint.c1687e85bf4cb311',
  'breakpoint.c17b52e2964bb149',
  'breakpoint.c25b4047f7533f80',
  'breakpoint.c3675c0d9a919a18',
  'breakpoint.c54ee73d8558b980',
  'breakpoint.c65d8dac411cc0c8',
  'breakpoint.c69099a0db6b97f8',
  'breakpoint.c86f2675dac5c0dc',
  'breakpoint.c8b7ad3416eb966a',
  'breakpoint.c945da2f1030a187',
  'breakpoint.cb00eeef4dffb704',
  'breakpoint.cbadf5c035b9e527',
  'breakpoint.cbf79b43caf559ab',
  'breakpoint.cc069635f2ac3560',
  'breakpoint.cc905f3650488551',
  'breakpoint.cd2e3b181127666b',
  'breakpoint.cd4a5c8e223f0efb',
  'breakpoint.cf5295f5c2273362',
  'breakpoint.cfa89968c79b6931',
  'breakpoint.cfc94dff4368dd1d',
  'breakpoint.d0793db4f5c8fb24',
  'breakpoint.d25def7a5dade814',
  'breakpoint.d28244cbad7281be',
  'breakpoint.d2de06ef181a0958',
  'breakpoint.d2ebde0206673a7e',
  'breakpoint.d35dfe2ce203a9c1',
  'breakpoint.d47794475bf97585',
  'breakpoint.d4c67d079c7d3659',
  'breakpoint.d5fcd576150d762c',
  'breakpoint.d6cfb2e1c8653948',
  'breakpoint.d91bd84de1ddcead',
  'breakpoint.d9fbb20bb6ae1e3d',
  'breakpoint.db05e0cf67a372c1',
  'breakpoint.dd6e419e96ae75b8',
  'breakpoint.df7d44783fec560e',
  'breakpoint.df8f99005c2bdc13',
  'breakpoint.dff010c5c49346aa',
  'breakpoint.e13b362f4fb49c4b',
  'breakpoint.e43dd30ab41e12a3',
  'breakpoint.e4bb42b01042b720',
  'breakpoint.e4fa62c6f50303b3',
  'breakpoint.e58a0100858a7446',
  'breakpoint.e605240bfc0e9704',
  'breakpoint.e79ef306b37db35f',
  'breakpoint.e912c901ecf76c8a',
  'breakpoint.e921d6d0ea5b7161',
  'breakpoint.ead42b8687a7d5cb',
  'breakpoint.ee8fc9c4b689eee8',
  'breakpoint.eef20b08966739d3',
  'breakpoint.ef0ba8480ede65ca',
  'breakpoint.f08a6763461f4312',
  'breakpoint.f09cb972d2b5caa9',
  'breakpoint.f332151199eb5e9d',
  'breakpoint.f39f8024e9466a19',
  'breakpoint.f573562b45bea1dd',
  'breakpoint.f6b30a159d967983',
  'breakpoint.f82186d969008abf',
  'breakpoint.fa322a669afc78fd',
  'breakpoint.fba2342d63419543',
  'breakpoint.fbdc87732a6e041d',
  'breakpoint.fc253136d71a8401',
  'breakpoint.fdbc329b887d9803',
  'breakpoint.fe39928562af0d2a',
]);

const NO_ELEMENT_TARGET_ACTIONS=new Set([
  'mock-clipboard','release-search','release-favorites','release-personal-feed',
  'release-images','release-discovery','release-weather','release-gallery-image',
  'set-profile','resize-viewport',
]);

const base={
  schema_version:BEHAVIOR_PACKET_SCHEMA,
  source_sha:PINNED_SOURCE_SHA,
  evidence_plane:'controlled-exact-source-runtime',
  production_state_claimed:false,
  review_status:'planned',
  reduced_motion:true,
  device_scale_factor:1,
  decision:'NOT_MERGED',
  normalization_allowed:false,
};
const actionContract=(input)=>{
  const action=input.kind==='search-submit'&&!input.selector
    ? {...input,selector:'[data-search-form]',scope:'page'}
    : input;
  return {
  ...action,
  target_requirement:NO_ELEMENT_TARGET_ACTIONS.has(action.kind)
    ? 'not-applicable-controlled-runtime'
    : action.kind==='scroll-window'
      ? 'required-viewport'
      : action.kind==='press'
        ? 'required-active-element'
        : 'required-element',
};
};
const step=(phase,actions=[],capture=true,expect={})=>({
  phase,actions:actions.map(actionContract),capture,
  expect:{root_observed:true,...(actions.length?{semantic_delta:true}:{}) ,...expect},
});
const plan=(id,family,route,root_selector,steps,extra={})=>Object.freeze({
  ...base,id:`behavior-packet.${id}`,family,route,root_selector,viewport:{width:390,height:844},
  capture_scope:'locator',steps,reachability:route.startsWith('/behavior-specimens/')
    ? 'controlled-exact-component-runtime'
    : 'candidate-runtime',breakpoint_probe_ids:[],
  coverage_refs:[`behavior-family.${family}`,...(extra.dynamic_region_ids||[]).map((item)=>`dynamic-region.${item}`)],...extra,
});
const blocker=(id,family,reason,extra={})=>Object.freeze({
  ...base,id:`behavior-packet.${id}`,family,route:null,root_selector:null,viewport:null,
  capture_scope:'none',steps:[],execution_status:'explicit-blocker',blocker_reason:reason,
  review_status:'not-applicable-no-raster',reachability:'exact-blocker',breakpoint_probe_ids:[],
  coverage_refs:[`behavior-family.${family}`,...(extra.dynamic_region_ids||[]).map((item)=>`dynamic-region.${item}`)],...extra,
});

export const BEHAVIOR_PACKET_PLANS=Object.freeze([
  // Mobile menu and disclosures (8)
  plan('menu-open-close','mobile-menu','/','[data-mobile-discovery-menu][data-reference4-fullscreen]',[
    step('closed'),step('open',[{kind:'click',selector:':scope > summary'}]),step('closed-after-close',[{kind:'click',selector:'[data-reference4-close]'}]),
  ],{capture_scope:'page'}),
  plan('menu-escape','mobile-menu','/','[data-mobile-discovery-menu][data-reference4-fullscreen]',[
    step('closed'),step('open',[{kind:'click',selector:':scope > summary'}]),step('closed-after-escape',[{kind:'press',key:'Escape'}]),
  ],{capture_scope:'page'}),
  plan('menu-collections-plane','mobile-menu','/','[data-mobile-discovery-menu][data-reference4-fullscreen]',[
    step('open',[{kind:'click',selector:':scope > summary'}]),step('collections',[{kind:'click',selector:'[data-reference4-collections-open]'}]),step('main-after-back',[{kind:'click',selector:'[data-reference4-collections-back]'}]),
  ],{capture_scope:'page'}),
  plan('menu-service-plane','mobile-menu','/','[data-mobile-discovery-menu][data-reference4-fullscreen]',[
    step('open',[{kind:'click',selector:':scope > summary'}]),step('service',[{kind:'click',selector:'[data-reference4-service-open]'}]),step('main-after-back',[{kind:'click',selector:'[data-reference4-service-back]'}]),
  ],{capture_scope:'page'}),
  plan('menu-short-scroll','mobile-menu','/','[data-mobile-discovery-menu][data-reference4-fullscreen]',[
    step('open-top',[{kind:'click',selector:':scope > summary'}]),step('open-bottom',[{kind:'scroll-element',selector:'[data-reference4-list]',edge:'end'}]),
  ],{capture_scope:'page',viewport:{width:390,height:678},breakpoint_probe_ids:['breakpoint.0d1227004996eb64','breakpoint.7dcef72ba1661e9b','breakpoint.d9fbb20bb6ae1e3d']}),
  plan('menu-tab-return','mobile-menu','/','[data-mobile-discovery-menu][data-reference4-fullscreen]',[
    step('open-focus-entry',[{kind:'click',selector:':scope > summary'}],true,{focus:'visible'}),
    step('tab-forward',[{kind:'press',key:'Tab'}],true,{focus:'changed-visible'}),
    step('shift-tab-return',[{kind:'press',key:'Shift+Tab'}],true,{focus:'returned-visible'}),
  ],{capture_scope:'page',breakpoint_probe_ids:['breakpoint.6a3f29cc4a7f92db']}),
  plan('menu-live-resize-short-restore','mobile-menu','/','[data-mobile-discovery-menu][data-reference4-fullscreen]',[
    step('open-standard',[{kind:'click',selector:':scope > summary'}],true,{viewport:{width:390,height:844}}),
    step('open-short',[{kind:'resize-viewport',width:390,height:678}],true,{viewport:{width:390,height:678}}),
    step('open-standard-restored',[{kind:'resize-viewport',width:390,height:844}],true,{viewport:{width:390,height:844}}),
  ],{capture_scope:'page',breakpoint_probe_ids:['breakpoint.0d1227004996eb64','breakpoint.7dcef72ba1661e9b','breakpoint.d9fbb20bb6ae1e3d']}),
  plan('time-nav-disclosure','disclosure','/behavior-specimens/time-nav/','[data-time-nav-disclosure]',[
    step('closed',[],true,{details_open:false}),
    step('open',[{kind:'click',selector:':scope > summary'}],true,{details_open:true,selector_visible:':scope .ke-time-nav__popover'}),
  ],{known_visual_conflict:'exact-time-popover-may-be-clipped-by-listing-nav-overflow; capture is scoped to the real disclosure and records descendant geometry'}),
  plan('city-picker','disclosure','/segodnya/','[data-mobile-v23-city-picker]',[
    step('closed'),step('open',[{kind:'click',selector:'summary'}]),step('selected',[{kind:'click',selector:'[data-mobile-v23-city]:not([data-mobile-v23-city="all"])'}]),
  ],{capture_scope:'page'}),
  plan('calendar-sheet','overlay','/vyhodnye/','[data-calendar-sheet]',[
    step('closed'),step('open',[{kind:'click',selector:'[data-calendar-open]',scope:'page'}]),step('next-month',[{kind:'click',selector:'[data-calendar-month-next]',scope:'page'}]),step('closed-after-button',[{kind:'click',selector:'[data-calendar-close]',scope:'page'}]),
  ],{capture_scope:'page'}),

  // Selection controls (4)
  plan('listing-city-filter','selection','/segodnya/','[data-listing-controls]',[
    step('all'),step('city-selected',[{kind:'click',selector:'[data-listing-city-input]:not([value="all"])',scope:'page'}]),
  ],{viewport:{width:1280,height:800}}),
  blocker('popular-category-filter','selection','PopularCategoryFilter has no pinned production consumer; source-only behavior cannot be promoted to runtime-observed.',{source_path:'src/components/listings/PopularCategoryFilter.astro'}),
  blocker('personal-filter-v1','selection','ListingPersonalFilter version=1 has no pinned non-lab consumer; a synthetic wrapper would not prove current consumer behavior.',{source_path:'src/components/ListingPersonalFilter.astro'}),
  plan('personal-filter-v2-floating','selection','/segodnya/','[data-listing-filter][data-listing-filter-version="2"]',[
    step('all'),step('personal',[{kind:'click',selector:'[data-listing-mode-button="personal"]'}]),step('all-restored',[{kind:'click',selector:'[data-listing-mode-button="all"]'}]),
  ],{viewport:{width:1280,height:800},before_navigation:[{kind:'seed-profile',mature:true,hidden_event_ids:[6767]},{kind:'set-listing-mode',mode:'all'}]}),

  // Rails and edge states (4)
  blocker('rail-empty','rail','No exact current route with a rendered zero-row rail exists; source emits an empty region only after client filtering and requires a dedicated reviewed fixture.'),
  blocker('rail-single','rail','No exact pinned current route/section with exactly one rendered MobileListingRailRow is available in the fixed candidate corpus.'),
  plan('rail-many-start-middle-end','rail','/segodnya/','[data-mobile-listing-row] .rail-window',[
    step('edge-start'),step('middle',[{kind:'scroll-element',edge:'middle'}]),step('edge-end',[{kind:'scroll-element',edge:'end'}]),
  ],{breakpoint_probe_ids:['breakpoint.4e4f246495ab0829','breakpoint.571728f2ece2f62b','breakpoint.3877feea65c3dc1b','breakpoint.db05e0cf67a372c1']}),
  blocker('rail-keyboard-home-end','rail','The exact MobileListingRailRow rail-window is focusable and horizontally scrollable, but the exact source has no keyboard handler and native Chromium End/Home leaves scrollLeft at 0. The failed runtime probe is retained as an accessibility blocker rather than replacing keyboard input with a programmatic scroll.',{source_path:'src/components/listings/MobileListingRailSurface.astro',breakpoint_probe_ids:['breakpoint.4e4f246495ab0829','breakpoint.571728f2ece2f62b','breakpoint.3877feea65c3dc1b','breakpoint.db05e0cf67a372c1'],blocked_states:['keyboard-end','keyboard-home-return'],blocks_ready:true,runtime_probe:{target:'[data-mobile-listing-row] .rail-window',focusable:true,key:'End',observed_scroll_left:0}}),

  // Sticky / fixed / collision (7)
  plan('sticky-mobile-title','sticky','/segodnya/','[data-mobile-listing-sticky-title]',[
    step('static'),step('approaching',[{kind:'scroll-window',y:180}]),step('pinned',[{kind:'scroll-to-selector',selector:'[data-mobile-v23-group]',offset:80}]),
  ],{capture_scope:'page'}),
  plan('sticky-mobile-collision','sticky','/populyarnoe/','[data-mobile-listing-sticky-title]',[
    step('static'),step('pinned',[{kind:'scroll-to-selector',selector:'[data-mobile-v23-group]',offset:80}]),step('next-group-collision',[{kind:'scroll-to-selector',selector:'[data-mobile-v23-group]:nth-child(2)',offset:74}]),
  ],{capture_scope:'page'}),
  plan('sticky-desktop-discovery','sticky','/segodnya/','[data-listing-discovery-rail]',[
    step('static'),step('pinned',[{kind:'scroll-window',y:340}]),step('leaving-page',[{kind:'scroll-window',edge:'end'}]),
  ],{capture_scope:'page',viewport:{width:1280,height:800}}),
  plan('sticky-weekend-nav','sticky','/vyhodnye/','[data-listing-time-nav]',[
    step('static',[],true,{root_geometry:'nonzero'}),
    step('pinned',[{kind:'scroll-window',y:420}],true,{root_geometry:'nonzero',window_scroll_changed:true}),
    step('group-collision',[{kind:'scroll-to-selector',selector:'[data-listing-time-group]',scope:'page',offset:120}],true,{root_geometry:'nonzero',window_scroll_changed:true}),
  ],{capture_scope:'page',viewport:{width:1280,height:800},visible_root_required:true}),
  plan('sticky-editorial-event','sticky','/lab/event-desktop/examples/editorial-photo/','[data-desktop-clean-event]',[
    step('static'),step('media-action-pinned',[{kind:'scroll-window',y:520}]),step('lower-content',[{kind:'scroll-window',y:1100}]),
  ],{capture_scope:'page',viewport:{width:1728,height:900}}),
  plan('sticky-split-event','sticky','/lab/event-desktop/examples/split-portrait/','[data-desktop-clean-event]',[
    step('static'),step('inline-action-pinned',[{kind:'scroll-window',y:520}]),step('lower-content',[{kind:'scroll-window',y:1100}]),
  ],{capture_scope:'page',viewport:{width:1728,height:900}}),
  plan('floating-filter-footer-collision','sticky','/segodnya/','[data-listing-filter][data-listing-filter-version="2"]',[
    step('visible'),step('near-footer',[{kind:'scroll-window',edge:'end'}]),
  ],{capture_scope:'page',viewport:{width:390,height:844},before_navigation:[{kind:'seed-profile',mature:true,hidden_event_ids:[6767]},{kind:'set-listing-mode',mode:'all'}]}),

  // CTA alternatives (6)
  plan('cta-editorial-stacked','cta','/lab/event-desktop/examples/editorial-photo/','[data-desktop-action-panel][data-action-layout="stacked"]',[step('baseline')],{viewport:{width:1728,height:900}}),
  plan('cta-split-inline','cta','/lab/event-desktop/examples/split-portrait/','[data-desktop-action-panel][data-action-layout="inline"]',[step('baseline')],{viewport:{width:1728,height:900}}),
  plan('cta-phone-success','cta','/lab/event-desktop/examples/cta-phone-invariant/','[data-desktop-action-panel]',[
    step('phone-hidden'),step('phone-copied',[{kind:'mock-clipboard',result:'success'},{kind:'click',selector:'[data-desktop-phone-copy]'}]),
  ],{viewport:{width:1728,height:900}}),
  plan('cta-phone-error','cta','/lab/event-desktop/examples/cta-phone-invariant/','[data-desktop-action-panel]',[
    step('phone-hidden'),step('phone-copy-error',[{kind:'mock-clipboard',result:'error'},{kind:'click',selector:'[data-desktop-phone-copy]'}]),
  ],{viewport:{width:1728,height:900}}),
  plan('cta-registration','cta','/lab/event-desktop/examples/cta-registration-invariant/','[data-desktop-action-panel]',[step('registration')],{viewport:{width:1728,height:900}}),
  plan('cta-sold-out','cta','/sobytiya/ekskursiya-zakulise-teatra-kaliningrad-5829/','[data-desktop-action-panel]',[step('sold-out-or-unavailable')],{viewport:{width:1728,height:900}}),

  // Three transport treatments on one exact fixture/environment (6)
  ...['departure_board_v1','route_strips_v1','next_departure_queue_v1'].flatMap((treatment)=>[
    plan(`transport-${treatment.replaceAll('_','-')}-baseline`,'transport','/behavior-specimens/transport/',`[data-transport-treatment="${treatment}"]`,[step('baseline')],{viewport:{width:391,height:900},container_width:391,before_navigation:[{kind:'select-treatment',treatment}]}),
    plan(`transport-${treatment.replaceAll('_','-')}-disclosure`,'transport','/behavior-specimens/transport/',`[data-transport-treatment="${treatment}"]`,[
      step('compact-closed',[],true,{details_open:false,selector_exists:'[data-transport-disclosure], [data-transport-queue-details]'}),
      step('compact-open',[{kind:'click',selector:'[data-transport-disclosure] summary, [data-transport-queue-details] summary'}],true,{details_open:true,root_height_changed:true}),
    ],{viewport:{width:389,height:900},container_width:389,before_navigation:[{kind:'select-treatment',treatment}],fixture_provenance:{kind:'controlled-preview-event-derived-options',base_event_id:5374,derived_with:'exact getKaupTransportSuggestion over bounded start-time variants',minimum_options:4,same_fixture_across_treatments:true},experiment_status:'unresolved-no-winner'}),
  ]),

  // Media (6)
  plan('media-real-5x4','media','/segodnya/','[data-mobile-rail-media-reason="safe_visual_landscape_5x4"]',[step('loaded-5x4')],{ratios:['5:4'],dynamic_region_ids:['mobile-listing-media'],media_provenance:{semantic_kind:'classified-visual-photo',source_binding:'real mobile listing rail consumer',ocr_or_document:false}}),
  plan('media-real-4x5','media','/sobytiya/ekskursiya-oplot-nezavisimosti-i-piva-kaliningrad-6686/','#discovery-feed [data-event-card][data-event-id="7023"] [data-card-media-shell]',[step('loaded-4x5')],{ratios:['4:5'],viewport:{width:390,height:844},dynamic_region_ids:['event-card-media'],media_provenance:{semantic_kind:'classified-visual-photo',source_binding:'real canonical EventCard consumer',ocr_or_document:false}}),
  plan('media-broken','media','/segodnya/','[data-mobile-listing-row] .event-media',[
    step('loading'),step('error',[{kind:'release-images',result:'error'}]),
  ],{network_profile:'deferred-images',dynamic_region_ids:['mobile-listing-media'],media_provenance:{semantic_kind:'controlled-image-error',source_binding:'real mobile listing rail image listener',ocr_or_document:false}}),
  plan('media-missing','media','/sobytiya/nauka-vsegda-kstati-progulka-s-uchenym-kaliningrad-6996/','[data-event-hero], [data-desktop-clean-event]',[step('missing-fallback')],{dynamic_region_ids:['event-card-media'],media_provenance:{semantic_kind:'missing-media-fallback',source_binding:'real event detail consumer',ocr_or_document:null}}),
  plan('media-tiny','media','/sobytiya/fotografii-moego-dedushki-semena-aniskova-kaliningrad-6757/','[data-event-hero], [data-desktop-clean-event]',[step('tiny-source')],{viewport:{width:1728,height:900},dynamic_region_ids:['event-card-media'],media_provenance:{semantic_kind:'low-resolution-photo',source_binding:'real event detail consumer',ocr_or_document:false}}),
  plan('media-primary-and-previews','media','/behavior-specimens/media-rail/','[data-behavior-media-fixture]',[step('large-primary-small-previews')],{viewport:{width:1024,height:900},media_provenance:{semantic_kind:'mixed-primary-poster-and-photo-previews',source_binding:'controlled exact EventMediaRail with exact event assets',ocr_or_document:'explicit-per-asset-metadata'}}),

  // Dynamic-region runtime closure. Every source matrix row is either captured
  // here/on an earlier packet or represented by an exact blocker below.
  plan('discovery-static-to-rerank','dynamic','/sobytiya/ekskursiya-oplot-nezavisimosti-i-piva-kaliningrad-6686/','[data-discovery-feed]',[
    step('static-fallback',[],true,{selector_exists:':scope > [data-event-card]'}),
    step('reranked',[{kind:'release-discovery',result:'success'}],true,{root_attribute:{name:'data-effective-algorithm-id',present:true}}),
  ],{viewport:{width:1280,height:800},network_profile:'discovery-success',dynamic_region_ids:['discovery-rerank']}),
  blocker('discovery-failure-static-fallback','dynamic','The exact discovery runtime intentionally preserves its already-rendered static fallback when rerank fetch fails. A controlled failed request produced no DOM, geometry, scroll or focus delta, so a second raster would be a mislabeled duplicate rather than an observable error state.',{source_path:'src/layouts/EventLayout.astro',dynamic_region_ids:['discovery-rerank'],blocked_states:['distinct-visible-error'],runtime_probe:{network_result:'controlled-error',visible_result:'unchanged-static-fallback',semantic_delta:false}}),
  plan('home-static-to-local-rerank','dynamic','/','[data-home-cold-start-feed]',[
    step('static-fallback',[],true,{root_attribute:{name:'data-home-feed-mode',value:'static_fallback'}}),
    step('local-rerank',[{kind:'set-profile',mature:true,liked_event_ids:[7008,7003,5658]}],true,{root_attribute:{name:'data-home-feed-mode',value:'local_rerank'}}),
  ],{viewport:{width:1280,height:800},dynamic_region_ids:['home-rerank']}),
  plan('popular-personalized-hidden-mobile','dynamic','/populyarnoe/','[data-popular-personalized]',[
    step('hidden-fail-closed',[],true,{root_visibility:'hidden'}),
  ],{capture_scope:'page',allow_hidden_root:true,dynamic_region_ids:['popular-personalized-row']}),
  plan('popular-personalized-visible-five-desktop','dynamic','/populyarnoe/','[data-popular-personalized]',[
    step('visible-five',[],true,{root_visibility:'visible',selector_count:{selector:':scope [data-popular-personalized-candidate]:not([hidden])',exact:5}}),
  ],{viewport:{width:1280,height:800},dynamic_region_ids:['popular-personalized-row'],before_navigation:[{kind:'seed-profile',mature:true,liked_event_ids:[7008,7003,5658]}]}),
  plan('weather-loading-ready','dynamic','/behavior-specimens/weather/','[data-weather-date-context]',[
    step('loading',[],true,{root_attribute:{name:'data-weather-state',value:'loading'}}),
    step('ready',[{kind:'release-weather',result:'success'}],true,{root_attribute:{name:'data-weather-state',value:'ready'},root_visibility:'visible'}),
  ],{capture_scope:'page',allow_hidden_root:true,network_profile:'weather-success',dynamic_region_ids:['weather'],breakpoint_probe_ids:['breakpoint.8b6ce655a24f4d8f','breakpoint.7eb95dfe4a10d51c','breakpoint.1c5991281f5bdc81','breakpoint.17cf0b9da60f5b7d']}),
  plan('weather-loading-hidden-unavailable','dynamic','/behavior-specimens/weather/','[data-weather-date-context]',[
    step('loading',[],true,{root_attribute:{name:'data-weather-state',value:'loading'}}),
    step('hidden-unavailable',[{kind:'release-weather',result:'error'}],true,{root_visibility:'hidden'}),
  ],{capture_scope:'page',allow_hidden_root:true,network_profile:'weather-error',dynamic_region_ids:['weather'],breakpoint_probe_ids:['breakpoint.8b6ce655a24f4d8f','breakpoint.7eb95dfe4a10d51c','breakpoint.1c5991281f5bdc81','breakpoint.17cf0b9da60f5b7d']}),
  plan('exhibitions-gallery-load-close-focus-return','dynamic','/vystavki/','[data-exhibitions-prototype]',[
    step('dialog-closed',[],true,{selector_closed:'[data-gallery]'}),
    step('dialog-open-loading',[{kind:'click',selector:'[data-gallery-open]',scope:'page'}],true,{selector_open:'[data-gallery]',selector_attribute:{selector:'[data-gallery-media]',name:'data-image-state',value:'loading'}}),
    step('dialog-open-loaded',[{kind:'release-gallery-image',result:'success'}],true,{selector_attribute:{selector:'[data-gallery-media]',name:'data-image-state',value:'loaded'}}),
    step('dialog-closed-focus-return',[{kind:'click',selector:'[data-gallery-close]',scope:'page'}],true,{selector_closed:'[data-gallery]',focus:'visible'}),
  ],{capture_scope:'page',viewport:{width:1280,height:800},network_profile:'gallery-success',dynamic_region_ids:['exhibitions-gallery'],breakpoint_probe_ids:['breakpoint.1ff6047bbf019dba','breakpoint.72545641023e2c7d']}),
  plan('exhibitions-gallery-error','dynamic','/vystavki/','[data-exhibitions-prototype]',[
    step('dialog-closed',[],true,{selector_closed:'[data-gallery]'}),
    step('dialog-open-loading',[{kind:'click',selector:'[data-gallery-open]',scope:'page'}],true,{selector_open:'[data-gallery]',selector_attribute:{selector:'[data-gallery-media]',name:'data-image-state',value:'loading'}}),
    step('dialog-open-error',[{kind:'release-gallery-image',result:'error'}],true,{selector_attribute:{selector:'[data-gallery-media]',name:'data-image-state',value:'error'},selector_visible:'[data-gallery-error]',selector_scope:'page'}),
  ],{capture_scope:'page',viewport:{width:1280,height:800},network_profile:'gallery-error',dynamic_region_ids:['exhibitions-gallery'],breakpoint_probe_ids:['breakpoint.72545641023e2c7d']}),
  plan('exhibitions-motion-no-preference','dynamic','/vystavki/','[data-exhibitions-prototype]',[
    step('motion-allowed-environment',[],true,{reduced_motion:false}),
  ],{capture_scope:'page',viewport:{width:1280,height:800},reduced_motion:false,dynamic_region_ids:['exhibitions-gallery'],breakpoint_probe_ids:['breakpoint.1ff6047bbf019dba']}),
  plan('listing-card-media-loading-loaded','media','/behavior-specimens/listing-media/','[data-listing-media-loading]',[
    step('loading'),step('loaded',[{kind:'release-images',result:'success'}],true,{root_attribute:{name:'data-listing-media-ready',value:'true'}}),
  ],{network_profile:'deferred-images',dynamic_region_ids:['listing-card-media'],media_provenance:{semantic_kind:'classified-photo-or-document-from-exact-event',source_binding:'controlled exact ListingEventCard consumer',ocr_or_document:'exact-event-metadata'}}),
  plan('listing-card-media-loading-error','media','/behavior-specimens/listing-media/','[data-listing-media-loading]',[
    step('loading'),step('error',[{kind:'release-images',result:'error'}],true,{root_attribute:{name:'data-listing-media-ready',value:'true'}}),
  ],{network_profile:'deferred-images',dynamic_region_ids:['listing-card-media'],media_provenance:{semantic_kind:'controlled-image-error',source_binding:'controlled exact ListingEventCard consumer',ocr_or_document:'exact-event-metadata'}}),
  blocker('auth-runtime-unobserved-state-transitions','dynamic','The exact global auth controller is a hidden runtime and the existing Search fixture proves only its signed-in consumer binding; checking, signed-out and initializer-error need a dedicated deterministic Supabase controller fixture before they can be called runtime-observed.',{source_path:'src/components/auth/StaticSiteAuthRuntime.astro',dynamic_region_ids:['auth-runtime'],blocked_states:['checking','signed_out','error']}),
  blocker('personalization-runtime-hidden-modes','dynamic','PersonalizationRuntime deliberately renders only a hidden marker. Its off, characterize and local-shadow modes have no visible raster surface; source characterization cannot be mislabeled as a UI capture.',{source_path:'src/components/personalization/PersonalizationRuntime.astro',dynamic_region_ids:['personalization-runtime'],blocked_states:['off','characterize','local-shadow']}),

  // Loading/recovery (9)
  plan('search-loading-result','loading','/poisk/','[data-authorized-search]',[
    step('idle'),step('loading',[{kind:'search-submit',query:'result'}]),step('result',[{kind:'release-search',result:'success'}]),
  ],{runtime_profile:'search-success',ratios:['5:4'],dynamic_region_ids:['search','auth-runtime']}),
  plan('search-loading-empty','loading','/poisk/','[data-authorized-search]',[
    step('idle'),step('loading',[{kind:'search-submit',query:'empty'}]),step('empty',[{kind:'release-search',result:'empty'}]),
  ],{runtime_profile:'search-empty',dynamic_region_ids:['search']}),
  plan('search-error-retry-result','loading','/poisk/','[data-authorized-search]',[
    step('idle'),step('loading-error',[{kind:'search-submit',query:'error'}]),step('error',[{kind:'release-search',result:'error'}]),step('retry-loading',[{kind:'search-submit',query:'result'}]),step('result',[{kind:'release-search',result:'success'}]),
  ],{runtime_profile:'search-error-retry',dynamic_region_ids:['search']}),
  plan('favorites-loading-result','loading','/izbrannoe/','[data-favorites-surface]',[
    step('loading'),step('result',[{kind:'release-favorites',result:'success'}]),
  ],{runtime_profile:'favorites-result',dynamic_region_ids:['favorites'],before_navigation:[{kind:'seed-profile',liked_event_ids:[7023]}]}),
  plan('favorites-loading-empty','loading','/izbrannoe/','[data-favorites-surface]',[
    step('loading'),step('empty',[{kind:'release-favorites',result:'success'}]),
  ],{runtime_profile:'favorites-empty',dynamic_region_ids:['favorites']}),
  plan('favorites-loading-error','loading','/izbrannoe/','[data-favorites-surface]',[
    step('loading'),step('error',[{kind:'release-favorites',result:'error'}]),
  ],{runtime_profile:'favorites-error',dynamic_region_ids:['favorites'],before_navigation:[{kind:'seed-profile',liked_event_ids:[7023]}]}),
  plan('personal-feed-popular','loading','/sobytiya/ekskursiya-oplot-nezavisimosti-i-piva-kaliningrad-6686/','[data-personal-feed-section]',[
    step('pending'),step('popular-fallback',[{kind:'release-personal-feed',result:'success'}]),
  ],{viewport:{width:1280,height:800},runtime_profile:'personal-feed-popular',dynamic_region_ids:['personal-feed']}),
  plan('personal-feed-personal','loading','/sobytiya/ekskursiya-oplot-nezavisimosti-i-piva-kaliningrad-6686/','[data-personal-feed-section]',[
    step('pending'),step('personal',[{kind:'release-personal-feed',result:'success'}]),
  ],{viewport:{width:1280,height:800},runtime_profile:'personal-feed-personal',dynamic_region_ids:['personal-feed'],before_navigation:[{kind:'seed-profile',mature:true,liked_event_ids:[7008,7003,5658]}]}),
  blocker('breakpoint-container-runtime-coverage-gap','geometry','The source matrix contains 293 exact breakpoint/container probes. Bounded packets exercise the critical menu, rail, event-family, weather and Exhibitions transitions, but the remaining source probes do not each have a truthful isolated runtime consumer; all exact probe IDs stay explicitly blocked rather than inferred from a family screenshot.',{breakpoint_probe_ids:ALL_BREAKPOINT_PROBE_IDS,coverage_refs:['breakpoint-container-matrix.all-293'],blocked_states:['per-probe-runtime-transition-unobserved'],blocks_ready:true}),
  blocker('personal-feed-unavailable','loading','Event-detail source falls back to deterministic popular content on ordinary fetch failure; an honest unavailable state additionally requires an unavailable renderer or empty validated corpus and is not reached by the pinned real corpus.',{source_path:'src/components/PersonalFeedSlot.astro',dynamic_region_ids:['personal-feed']}),
]);

export function buildBehaviorPacketRegistry(){
  return {schema_version:BEHAVIOR_PACKET_SCHEMA,source_sha:PINNED_SOURCE_SHA,plans:BEHAVIOR_PACKET_PLANS.map((row)=>structuredClone(row))};
}

export function expectedRasterCount(registry=buildBehaviorPacketRegistry()){
  return registry.plans.reduce((sum,row)=>sum+row.steps.filter((item)=>item.capture).length,0);
}
