#!/usr/bin/env node
import { createHash } from 'node:crypto';
import { readdir, readFile, writeFile } from 'node:fs/promises';
import { extname, join, relative, resolve } from 'node:path';
import { fileURLToPath, pathToFileURL } from 'node:url';

export const EVENT_SEARCH_REVISION_FILE = 'search-backend-revision.generated.ts';
const HASH_DOMAIN = Buffer.from('kenigevents-event-search-source-tree-v1\0', 'utf8');
const SOURCE_EXTENSIONS = new Set(['.ts', '.tsx', '.js', '.mjs', '.json']);
const TEST_FILE_RE = /\.test\.(?:ts|tsx|js|mjs)$/u;

const asPath = (value) => value instanceof URL ? fileURLToPath(value) : resolve(String(value));
const portable = (value) => value.split('\\').join('/');

async function deployableFiles(root, directory = root) {
  const names = await readdir(directory, { withFileTypes: true });
  const files = [];
  for (const entry of names) {
    const absolute = join(directory, entry.name);
    if (entry.isSymbolicLink()) throw new Error('event_search_revision_symlink_forbidden');
    if (entry.isDirectory()) {
      files.push(...await deployableFiles(root, absolute));
      continue;
    }
    if (!entry.isFile()) continue;
    const path = portable(relative(root, absolute));
    if (path === EVENT_SEARCH_REVISION_FILE || TEST_FILE_RE.test(path)
      || !SOURCE_EXTENSIONS.has(extname(path))) continue;
    files.push(path);
  }
  return files.sort((left, right) => left.localeCompare(right, 'en'));
}

export async function computeEventSearchRevision(sourceRoot) {
  const root = asPath(sourceRoot);
  const files = await deployableFiles(root);
  if (files.length === 0) throw new Error('event_search_revision_source_empty');
  const hash = createHash('sha256');
  hash.update(HASH_DOMAIN);
  for (const path of files) {
    const bytes = await readFile(join(root, path));
    const pathBytes = Buffer.from(path, 'utf8');
    hash.update(Buffer.from(`${pathBytes.length}:`, 'ascii'));
    hash.update(pathBytes);
    hash.update(Buffer.from(`\0${bytes.length}:`, 'ascii'));
    hash.update(bytes);
    hash.update(Buffer.from('\0', 'ascii'));
  }
  return Object.freeze({
    schema_version: 'event_search_source_revision_v1',
    revision: `sha256:${hash.digest('hex')}`,
    files: Object.freeze(files),
  });
}

export function renderEventSearchRevisionModule(computed) {
  const revision = String(computed?.revision || '');
  if (!/^sha256:[0-9a-f]{64}$/u.test(revision)) throw new Error('event_search_revision_invalid');
  return `// Generated by scripts/generate_event_search_revision.mjs. Do not edit.\nexport const SEARCH_BACKEND_REVISION = "${revision}";\n`;
}

export async function verifyEventSearchRevision({ sourceRoot, generated } = {}) {
  const computed = await computeEventSearchRevision(sourceRoot);
  const expected = renderEventSearchRevisionModule(computed);
  let actual = '';
  try { actual = await readFile(asPath(generated), 'utf8'); } catch { /* stale/missing */ }
  if (actual !== expected) throw new Error('event_search_backend_revision_stale');
  return computed;
}

async function main(argv = process.argv.slice(2)) {
  if (argv.some((value) => value !== '--check')) throw new Error('event_search_revision_argument_invalid');
  const sourceRoot = new URL('../supabase/functions/event-search/', import.meta.url);
  const generated = new URL(`../supabase/functions/event-search/${EVENT_SEARCH_REVISION_FILE}`, import.meta.url);
  if (argv.includes('--check')) {
    const computed = await verifyEventSearchRevision({ sourceRoot, generated });
    process.stdout.write(`${computed.revision}\n`);
    return;
  }
  const computed = await computeEventSearchRevision(sourceRoot);
  await writeFile(generated, renderEventSearchRevisionModule(computed), { mode: 0o644 });
  process.stdout.write(`${computed.revision}\n`);
}

if (process.argv[1] && pathToFileURL(resolve(process.argv[1])).href === import.meta.url) {
  main().catch((error) => {
    process.stderr.write(`${String(error?.message || 'event_search_revision_failed')}\n`);
    process.exitCode = 1;
  });
}
