from __future__ import annotations

import html
import math
from pathlib import Path

from .config import RunConfig
from .contracts import Candidate, LinePrimitive
from .dependencies import require_module


def _path_d(line: LinePrimitive, scale: float, ox: float, oy: float) -> str:
    if not line.points:
        return ""
    parts = [f"M {line.points[0][0] * scale + ox:.2f} {line.points[0][1] * scale + oy:.2f}"]
    for point in line.points[1:]:
        parts.append(f"L {point[0] * scale + ox:.2f} {point[1] * scale + oy:.2f}")
    return " ".join(parts)


def _sketch_points(line: LinePrimitive, *, line_index: int, pass_index: int) -> list[tuple[float, float]]:
    if len(line.points) <= 1:
        return line.points
    amplitude = 0.85 + 0.22 * pass_index
    phase = (line_index + 1) * 0.73 + pass_index * 1.91
    out: list[tuple[float, float]] = []
    for point_index, (x, y) in enumerate(line.points):
        if point_index in {0, len(line.points) - 1}:
            anchor_scale = 0.45
        else:
            anchor_scale = 1.0
        dx = math.sin(phase + point_index * 1.37) * amplitude * anchor_scale
        dy = math.cos(phase * 0.81 + point_index * 1.13) * amplitude * anchor_scale
        out.append((x + dx, y + dy))
    return out


def _line_render_variants(line: LinePrimitive, *, line_index: int, stroke_style: str) -> list[LinePrimitive]:
    if stroke_style != "sketch":
        return [line]
    passes = 3 if line.role in {"silhouette", "roofline", "structure"} and line.priority >= 6 else 2
    return [
        LinePrimitive(
            _sketch_points(line, line_index=line_index, pass_index=pass_index),
            role=line.role,
            priority=line.priority,
            source=f"{line.source}:sketch_pass_{pass_index}",
            confidence=line.confidence,
        )
        for pass_index in range(passes)
    ]


def write_svg(candidate: Candidate, config: RunConfig, path: str | Path, *, source_size: tuple[int, int]) -> Path:
    out = Path(path)
    out.parent.mkdir(parents=True, exist_ok=True)
    vb_w, vb_h = config.style.viewbox
    scale, ox, oy = _composition_transform(candidate.lines, (vb_w, vb_h), source_size)
    stroke = html.escape(config.style.stroke_color)
    width = float(config.style.stroke_width) * float(candidate.parameters.get("stroke_width_scale") or 1.0)
    lines_xml = []
    stroke_style = str(config.style.stroke_style or "clean").strip().lower()
    for idx, line in enumerate(candidate.lines):
        for pass_idx, render_line in enumerate(_line_render_variants(line, line_index=idx, stroke_style=stroke_style)):
            d = _path_d(render_line, scale, ox, oy)
            if not d:
                continue
            priority_width = width
            if line.role in {"silhouette", "roofline"}:
                priority_width = width * 1.15
            elif line.priority <= 4:
                priority_width = width * 0.78
            opacity = 0.96 if stroke_style != "sketch" else max(0.72, 0.90 - pass_idx * 0.07)
            lines_xml.append(
                "  "
                f'<path class="line role-{html.escape(line.role)}" data-source="{html.escape(render_line.source)}" '
                f'd="{d}" fill="none" stroke="{stroke}" stroke-width="{priority_width:.2f}" '
                f'stroke-opacity="{opacity:.2f}" '
                'stroke-linecap="round" stroke-linejoin="round" vector-effect="non-scaling-stroke" />'
            )
    svg = "\n".join(
        [
            '<?xml version="1.0" encoding="UTF-8"?>',
            f'<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 {vb_w} {vb_h}" width="{vb_w}" height="{vb_h}">',
            " <metadata>Generated by contour_svg neural-first pipeline; no raster image is embedded.</metadata>",
            *lines_xml,
            "</svg>",
            "",
        ]
    )
    out.write_text(svg, encoding="utf-8")
    candidate.svg_path = out
    if candidate.candidate_svg is not None:
        candidate.candidate_svg.svg_path = out
    return out


def _composition_transform(lines: list[LinePrimitive], viewbox: tuple[int, int], source_size: tuple[int, int]) -> tuple[float, float, float]:
    vb_w, vb_h = viewbox
    points = [point for line in lines for point in line.points]
    if points:
        min_x = min(p[0] for p in points)
        max_x = max(p[0] for p in points)
        min_y = min(p[1] for p in points)
        max_y = max(p[1] for p in points)
    else:
        min_x, min_y = 0.0, 0.0
        max_x, max_y = float(source_size[0]), float(source_size[1])
    src_w = max(1.0, max_x - min_x)
    src_h = max(1.0, max_y - min_y)
    target_w = vb_w * 0.84
    target_h = vb_h * 0.84
    scale = min(target_w / src_w, target_h / src_h)
    used_w = src_w * scale
    used_h = src_h * scale
    ox = (vb_w - used_w) / 2 - min_x * scale
    oy = (vb_h - used_h) / 2 - min_y * scale
    return scale, ox, oy


def render_preview(svg_path: str | Path, png_path: str | Path, *, background: str = "#6E1F12") -> Path:
    cairosvg = require_module("cairosvg", "cairosvg")
    png = Path(png_path)
    png.parent.mkdir(parents=True, exist_ok=True)
    parent_bg = None if background == "transparent" else background
    cairosvg.svg2png(url=str(svg_path), write_to=str(png), background_color=parent_bg)
    return png
